CREATE TABLE IF NOT EXISTS user_filmorate (
    id       INTEGER             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(50),
    login    VARCHAR(50),
    name     VARCHAR(50),
    birthday TIMESTAMP
);

CREATE TABLE IF NOT EXISTS  friendship (
    id INTEGER REFERENCES  user_filmorate(id),
    id_friend INTEGER REFERENCES  user_filmorate(id)
);

CREATE TABLE IF NOT EXISTS  mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS film (
    id       INTEGER             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50),
    description    VARCHAR(300),
    releaseDate     TIMESTAMP,
    duration INT,
    id_mpa INT REFERENCES  mpa(id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    id_film INTEGER REFERENCES  film(id),
    id_user INTEGER REFERENCES  user_filmorate(id)
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER  PRIMARY KEY,
    name VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS film_genre (
    id_film INTEGER REFERENCES  film(id),
    id_genre INTEGER REFERENCES genre(id)
);

